acc_steps: 4
autocast: true
cross_val_num: null
device: cuda
global_step: 0
image_size: 384
log_dir: ./experiments/vit_small
lr: 0.0001
model_name: vit_small_r26_s32_384.augreg_in21k_ft_in1k
n_epochs: 50
n_warmup_steps: 1000
p_neg_class: 1.0
p_resize: 0.5
real_epoch_num: 50
scale: 1.0
seed: 5
split_col: split_dbscan
train_batch_size: 4
valid_batch_size: 4
wd: 0.0001
workers: 6
