acc_steps: 1
autocast: true
cross_val_num: null
device: cuda
global_step: 0
image_size: 512
log_dir: ./experiments/vit_giant
lr: 1.0e-06
model_name: vit_giant_patch14_dinov2.lvd142m
n_epochs: 50
n_warmup_steps: 1000
p_neg_class: 1.0
p_resize: 0.5
real_epoch_num: 50
scale: 1.0
seed: 5
split_col: split_dbscan
train_batch_size: 4
valid_batch_size: 4
wd: 0.0001
workers: 6
